baseURL = 'https://hugo-test.com/'
title = 'Förderverein Kita Buddelflink'
theme = "hermit-V2"

defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true

languageCode = 'de-DE'

[params]
  description = "CHANGE ME SITE DESCRIPTION"
  footerHideThemeName = false
  homeSubtitlePrinter = false
  readTime         = true
  scrollToTop      = true
  bgImg = "../images/background.jpg"
  footerCopyright = ' <a href="https://opensource.org/licenses/MIT" target="_blank" rel="noopener">MIT License</a>'


  [params.dateform]
    CopyrightDate = "2006"
    LongDate = "2. Jan, 2006"
    ShortDate = "2. Jan"
    NumDateShort = "02.01.2006"
    NumDateLong = "02.01.2006 15:04"

[menu]
  [[menu.main]]
    name = "Aktuelles"
    url = "aktuelles/"
    weight = 10
  [[menu.main]]
    name = "Über uns"
    url = "about/"
    weight = 20
  [[menu.main]]
    name = "Kontakt"
    url = "contact/"
    weight = 30
